test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,6 +35,17 @@ jobs:
           echo "Configured Git user.name: $(git config --global user.name)"
           echo "Configured Git user.email: $(git config --global user.email)"
 
+      - name: Check if Email is Correct
+       run: |
+        if [[ "${{ env.GITHUB_EMAIL }}" == "rabisiddique27@gmail.com" ]]; then
+          echo "Email matches rabisiddique27@gmail.com"
+        else
+          echo "Email does not match"
+          exit 1 # Optional: fail the workflow if the email does not match
+        fi
+
+
+
       - name: Release with release-it
         run: npx release-it
         env:
